### ISSUE TITLE
Error building 

### ISSUE THREAD

**Issue by psyduckc** [Arisstath/raknet-dissector#10]
I followed the steps exactly and when I tried to build the project with qt, this is the error I got. The stacktrace is below.
`C:\Users\Admin>%GOPATH%/bin/qtdeploy build %GOPATH%/src/github.com/gskartwii/roblox-dissector
time="2019-03-29T12:06:22-04:00" level=panic msg="failed to recognize build target C:\\Users\\Admin\\go/src/github.com/gskartwii/roblox-dissector"
panic: (*logrus.Entry) (0x917c00,0xc0000c9570)

goroutine 1 [running]:
github.com/sirupsen/logrus.Entry.log(0xc000056120, 0xc000108f90, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        C:/Users/Admin/go/src/github.com/sirupsen/logrus/entry.go:240 +0x2d5
github.com/sirupsen/logrus.(*Entry).Log(0xc0000c9500, 0x0, 0xc000091b98, 0x1, 0x1)
        C:/Users/Admin/go/src/github.com/sirupsen/logrus/entry.go:269 +0xf4
github.com/sirupsen/logrus.(*Entry).Logf(0xc0000c9500, 0xc000000000, 0x94f4c1, 0x23, 0xc000091c48, 0x1, 0x1)
        C:/Users/Admin/go/src/github.com/sirupsen/logrus/entry.go:315 +0xeb
github.com/sirupsen/logrus.(*Logger).Logf(0xc000056120, 0x0, 0x94f4c1, 0x23, 0xc000091c48, 0x1, 0x1)
        C:/Users/Admin/go/src/github.com/sirupsen/logrus/logger.go:145 +0x9d
github.com/sirupsen/logrus.(*Logger).Panicf(...)
        C:/Users/Admin/go/src/github.com/sirupsen/logrus/logger.go:186
github.com/therecipe/qt/internal/utils.CheckBuildTarget(0xc00009a040, 0x3b)
        C:/Users/Admin/go/src/github.com/therecipe/qt/internal/utils/env.go:119 +0x48e
main.main()
        C:/Users/Admin/go/src/github.com/therecipe/qt/cmd/qtdeploy/main.go:104 +0x4cc`

**Comment by Gskartwii** [comment]
Sorry for the confusion, there seems to be an error in the README. You actually have to run two commands:

```
cd %GOPATH%/src/github.com/gskartwii/roblox-dissector
%GOPATH%/bin/qtdeploy build windows
```

Also, if you haven't already, make sure that you have also run the initial setup for therecipe's qt (`qtsetup full`).

Feel free to add a comment if you have any further issues.
