### ISSUE TITLE
CFrame parser/serializer doesn't work correctly

### ISSUE THREAD

**Issue by Gskartwii** [Arisstath/raknet-dissector#19]
Sometimes CFrame properties aren't serialized correctly. This can be demonstrated by joining [Fencing](https://www.roblox.com/games/12109643/Fencing) in WinDivert proxy mode and observing how the foil tool's Grip appears to be malformed.

**Comment by Arisstath** [comment]
[sala_repro.zip](https://github.com/Gskartwii/roblox-dissector/files/4594587/sala_repro.zip)

Example of a place that Sala can't parse correctly.

Part names `DUMPEDWRONGLY`, `WRONGDUMPOPPOS`
