### ISSUE TITLE
Breaking changes to "rbxapi" depedency

### ISSUE THREAD

**Issue by Anaminus** [Arisstath/raknet-dissector#2]
Hi! I'm going to be making several backwards-incompatible changes to the [rbxapi](https://github.com/RobloxAPI/rbxapi) package, which this project depends on through [your fork of the rbxfile package](https://github.com/Gskartwii/rbxfile).

I recommend forking or vendoring the current version of rbxapi. Alternatively, I've tagged the current version of rbxapi as `v1.0`, if you would like to use tooling to build against that instead.

**Comment by Gskartwii** [comment]
Thanks for the heads up! I'll be sure to keep this in mind.

**Comment by Gskartwii** [comment]
I've updated my fork of rbxfile to be compatible with the new rbxapi package. So far there haven't been any issues, so I'm going to close the issue until such problems arise.
