### ISSUE TITLE
Not sure how to run this

### ISSUE THREAD

**Issue by knicholes** [Arisstath/raknet-dissector#3]
Is there any chance you can add more details to how to use this tool?  I'm not clear about which values to enter when starting the proxy, whether or not it's necessary to start the local server, and what you mean by starting with Roblox Studio or through the dissector.  I'm trying to find a tool that can help me find my position in Roblox.

**Comment by alureon** [comment]
Not sure if this tool is updated for the latest network protocol, but you most likely want to capture from a live interface (depends on your specific circumstances, though). It's not necessary to start the local server if you just want to extract position values from a running Roblox instance.

**Comment by Gskartwii** [comment]
At the moment, I'm not updating this repository due to a lack of time, and some unresolved questions regarding potential abuse (i.e. stealing games).

**Comment by knicholes** [comment]
Could you please provide me with a starting point for decoding the latest protocol?  Or do you know of another library?  I'm trying to do some research with reinforcement learning.

**Comment by Gskartwii** [comment]
I'm thinking about releasing a newer version of this library in the near future. Stay tuned!

**Comment by Gskartwii** [comment]
I have released [v0.6](https://github.com/Gskartwii/roblox-dissector/releases/tag/v0.6), which contains lots of improvements and should work with the newest protocol for the most part. Its source is available on the [windows-proxy](https://github.com/Gskartwii/roblox-dissector/tree/windows-proxy) branch.

To run the program:
1. Download windows.zip and extract it.
2. Run roblox-dissector.exe
3. Choose "Capture -> From live interface..."
4. If you don't know which interface to choose, just pick one and keep on reading.
5. Start the capture
6. Join a Roblox game
7. You should see packets appearing on the screen. If not, go back to step 3 and choose a different interface.

**Comment by Gskartwii** [comment]
I'm assuming this issue is resolved. Please reopen it if not.

**Comment by atomiclucky** [comment]
> I have released [v0.6](https://github.com/Gskartwii/roblox-dissector/releases/tag/v0.6), which contains lots of improvements and should work with the newest protocol for the most part. Its source is available on the [windows-proxy](https://github.com/Gskartwii/roblox-dissector/tree/windows-proxy) branch.
> 
> To run the program:
> 
> 1. Download windows.zip and extract it.
> 2. Run roblox-dissector.exe
> 3. Choose "Capture -> From live interface..."
> 4. If you don't know which interface to choose, just pick one and keep on reading.
> 5. Start the capture
> 6. Join a Roblox game
> 7. You should see packets appearing on the screen. If not, go back to step 3 and choose a different interface.

does the latest version work with the newest roblox update? I tried selecting every live interface, but to no success

**Comment by Arisstath** [comment]
Yes it does work with the latest Roblox.

**Comment by atomiclucky** [comment]
Another one quick question: how do you get .crt and .pem files for the WINDIVERT proxy? Do you need to generate them with OpenSSL?
