### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ghost** [Arisstath/raknet-dissector#37]
When i try to open a pcap file it crashes at 9% and crashes instantly when i open roblox on the live interference

**Comment by ghost** [comment]
Open command prompt in the same folder as the dissector binary and enter this:
`roblox-dissector.exe 2>> error.log`

Reproduce the crash and then post the error.log here.

**Comment by ghost** [comment]
When i open pcap file:
`
panic: runtime error: index out of range

goroutine 27 [running]:
github.com/Gskartwii/roblox-dissector/peer.(*SplitPacketBuffer).addPacket(...)
	/media/sf_GOPATH0/src/github.com/Gskartwii/roblox-dissector/peer/SplitPackets.go:61
github.com/Gskartwii/roblox-dissector/peer.(*DefaultPacketReader).addSplitPacket(0xc0000442a0, 0xc00042caa0, 0x98)
	/media/sf_GOPATH0/src/github.com/Gskartwii/roblox-dissector/peer/SplitPackets.go:93 +0xaf5
github.com/Gskartwii/roblox-dissector/peer.(*DefaultPacketReader).handleSplitPacket(0xc0000442a0, 0xc00042caa0, 0xb, 0xc00042c960, 0xc000570bc0)
	/media/sf_GOPATH0/src/github.com/Gskartwii/roblox-dissector/peer/SplitPackets.go:101 +0x5d
github.com/Gskartwii/roblox-dissector/peer.(*DefaultPacketReader).readReliable(0xc0000442a0, 0xc00042c960)
	/media/sf_GOPATH0/src/github.com/Gskartwii/roblox-dissector/peer/PacketReader.go:244 +0x191
github.com/Gskartwii/roblox-dissector/peer.(*DefaultPacketReader).ReadPacket(0xc0000442a0, 0xc00028002a, 0x1e, 0x1e, 0xc00042c960)
	/media/sf_GOPATH0/src/github.com/Gskartwii/roblox-dissector/peer/PacketReader.go:321 +0x37a
main.(*CaptureContext).Capture(0xc0003f6040, 0xc129a0, 0xc0003f6000, 0xc000180030, 0xc0006b66e0, 0x1, 0x0)
	/media/sf_GOPATH0/src/github.com/Gskartwii/roblox-dissector/FileCapture.go:163 +0x351
main.(*CaptureContext).CaptureFromHandle(0xc0003f6040, 0xc129a0, 0xc0003f6000, 0xc0003f4000, 0x0, 0xc0006b66e0, 0x0, 0x0)
	/media/sf_GOPATH0/src/github.com/Gskartwii/roblox-dissector/FileCapture.go:185 +0x10f
main.(*CaptureSession).CaptureFromHandle(...)
	/media/sf_GOPATH0/src/github.com/Gskartwii/roblox-dissector/CaptureSession.go:132
main.(*DissectorWindow).CaptureFromFile.func2(0xc00015a5a0, 0xc0003f4000, 0xc00015a500, 0xc0006b66e0, 0xc00019c000)
	/media/sf_GOPATH0/src/github.com/Gskartwii/roblox-dissector/DissectorWindow.go:121 +0x7d
created by main.(*DissectorWindow).CaptureFromFile
	/media/sf_GOPATH0/src/github.com/Gskartwii/roblox-dissector/DissectorWindow.go:120 +0x3d9
`

**Comment by Gskartwii** [comment]
Thanks for reporting the issue! The log is indeed very useful for debugging. If possible, could you also upload the offending PCAP file and specify how it has been produced (i.e. captured from vanilla Roblox or a different RakNet implementation)? From the looks of it, the crash could be caused by a malformed packet.

**Comment by Gskartwii** [comment]
Since the the account that reported this issue is now suspended, I'll be closing this issue. If a similar problem is encountered, please open a new issue.
