### ISSUE TITLE
Choose network interface not closing

### ISSUE THREAD

**Issue by mttsner** [Arisstath/raknet-dissector#47]
# Issue
When choosing an interface and clicking the Capture button, the Choose network interface prompt goes into a state, where it still exists but cannot be closed, opened or viewed. Only way to see the hidden prompt is to hover over sala in the windows taskbar.

## Current behavior
After Choosing your interface and clicking Capture, the prompt goes into a hidden state.

## Expected behavior
After choosing your interface and clicking Capture, the prompt closes itself.

### Hovered
![hovered](https://user-images.githubusercontent.com/42277794/80747024-6e621e00-8b2b-11ea-92f4-2f810794564f.PNG)

### Not hovered
![not_hovered](https://user-images.githubusercontent.com/42277794/80747344-fba57280-8b2b-11ea-9c2e-4f9ecca6d9c3.PNG)

**Comment by Gskartwii** [comment]
Thanks for reporting!
