### ISSUE TITLE
ID_CLUSTER Parsing issue

### ISSUE THREAD

**Issue by Arisstath** [Arisstath/raknet-dissector#50]
Example place: https://www.roblox.com/games/3303871986/testplace

![image](https://user-images.githubusercontent.com/11246626/81400519-fbadff80-9135-11ea-8617-f216110240fa.png)

**Comment by Gskartwii** [comment]
Apparently, the reproduction place isn't available on PC:
![image](https://user-images.githubusercontent.com/6651822/81813719-8032c080-9530-11ea-92b6-b8f08a322b42.png)

**Comment by Arisstath** [comment]
Sorry, it's now fixed.
