### ISSUE TITLE
Fix windivert support

### ISSUE THREAD

**Issue by ronalddawson** [Arisstath/raknet-dissector#55]
Needs a new method of detecting the handshake.

**Comment by Gskartwii** [comment]
I'm working on this at the moment. It will require the WinDivert 2 filter extensions, so updating the bindings correctly is not trivial.

**Comment by Gskartwii** [comment]
This is now fixed for the most part (works on Fencing). There might still be bugs, but basic functionality is working. However, the GitHub workflow doesn't currently handle WinDivert. Once that's sorted out, I will close the issue.
