### ISSUE TITLE
Windivert Capture mode, 260 disconnect due to union

### ISSUE THREAD

**Issue by Zwolf8** [Arisstath/raknet-dissector#56]
In windivert capture if you join a game with a union in it you get disconnected.

This place file simply contains a baseplate with a default brick that is unioned.

[SalaUnionIssueRepro.zip](https://github.com/Gskartwii/roblox-dissector/files/4774309/SalaUnionIssueRepro.zip)

**Comment by Gskartwii** [comment]
Thanks for reporting. This probably has something to do with the SharedString format.
